name: Docs

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-docs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install docs dependencies
        run: uv sync --locked --group docs

      - name: Install bash kernel
        run: uv run python -m bash_kernel.install

      - name: Install bcftools
        run: |
          sudo apt-get update && sudo apt-get install -y bcftools jq

      - name: Build Docs
        run: |
          make -C docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build-docs
    if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
    permissions:
        pages: write
        id-token: write

    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
